version: '3.7'

services:
  audio_db:
    image: postgres:13
    container_name: audio_db
    restart: on-failure
    environment:
      PGTZ: Africa/Lagos
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $DB_EXTERNAL_PORT:5432
    volumes:
      - $PWD/queries:/queries
      - $PWD/queries/init.sql:/docker-entrypoint-initdb.d/init.sql
      - audio_db_data:/var/lib/postgresql/data
    networks:
      - audio_network

networks:
  audio_network:
    driver: bridge

volumes:
  audio_db_data:
